### ISSUE TITLE
When i run client program  never ask me for file name 

### ISSUE THREAD

**Issue by hasnentai** [sam95/7th-sem-cn-lab#1]
When i run client program  never ask me for file name

**Comment by sam95** [comment]
Hi,
When I run the client, I get a message saying `enter filename`. Not sure why you are not able to get it.
Some points to be noted.

1. We need to run the server first and then the client. Server should be waiting for a request from the client. 

2. Open two different terminals. Compile the server and run the server.

       gcc 9s.c
       ./a.out

3. In the other terminal. Compile the client and run the client.

       gcc 9c.c
       ./a.out

4. Please note that you need to compile the client before running it. Or else you would be running the executable of the server itself.

5. Provide the file name to the client. And the server processes it, and returns the data to the client and client prints it.

Shoot me a mail at `sameerasy7@gmail.com` or ping me on hangouts. I'll try to help you out.

**Comment by sam95** [comment]
I am closing the above issue. Please feel free to open if you face it again. Thanks a lot for dropping by!
